In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)

In [3]:
my_list = list(range(1_000_000))

In [5]:
%timeit my_arr2 = my_arr * 2

1.11 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%timeit my_list2 = [x * 2 for x in my_list]

76.1 ms ± 2.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


##ndarray

In [8]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [9]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [10]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data.shape

(2, 3)

In [13]:

data.dtype

dtype('float64')

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [19]:
arr2 = np.array(data2)

In [20]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr2.ndim

2

In [22]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int64')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
np.empty((2,3,2))

array([[[4.81561763e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [38]:
np.empty(4)

array([6. , 7.5, 8. , 1. ])

In [39]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
np.full(2,3)

array([3, 3])

In [47]:
np.full((4,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [48]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [49]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [50]:
arr1.dtype

dtype('float64')

In [51]:
arr2.dtype

dtype('int32')

In [52]:
arr = np.array([1,2,3,4,5])

In [53]:
arr.dtype

dtype('int64')

In [55]:
float_arr = arr.astype(np.float64)

In [56]:
float_arr

array([1., 2., 3., 4., 5.])

In [57]:
float_arr.dtype

dtype('float64')

In [58]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [59]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [60]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [61]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [62]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [63]:
int_array = np.arange(10)

In [65]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [66]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
zeros_uint32 = np.zeros(8, dtype = 'u4')

In [68]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Arithmetic with NumPy Arrays

In [69]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

In [70]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [74]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [75]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [76]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [77]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [78]:
arr = np.arange(10)

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr[5]

5

In [81]:
arr[5:8]

array([5, 6, 7])

In [82]:
arr[5:8] = 12

In [83]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [85]:
arr_slice = arr[5:8]

In [86]:
arr_slice

array([12, 12, 12])

In [87]:
arr_slice[1] = 12345

In [88]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [89]:
arr_slice[:] = 64

In [90]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [91]:
arr[5:8].copy()

array([64, 64, 64])

In [93]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [94]:
arr2d[2]

array([7, 8, 9])

In [95]:
arr2d[0][2]

3